name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.3.0
  mailer: ^6.2.0
  pdf: ^3.10.1
  path_provider: ^2.0.11
  flutter_vector_icons: any
  flutter_file_dialog: ^3.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  image_picker: ^0.8.7+4
  table_calendar: ^3.0.9
  crypto: ^3.0.1
  http: ^1.4.0
  provider: ^6.0.0
  shamsi_date: ^1.1.1
  shared_preferences: ^2.2.0
  file_picker: ^10.3.1
  open_file: ^3.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
       # انیمیشن اژدها در پس زمینه
    - lib/assets/taha.png
    - lib/assets/mehdi.png
    - lib/assets/alireza.png
