name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Flutter with exact version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.8'   # Flutter version with Dart >=3.8
          cache: false                # Prevent cache issues

      # 3. Disable Flutter analytics
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 6. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # iOS job (requires Mac runner + Apple Developer account)
  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.8'
          cache: false

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: build/ios/ipa/*.ipa
