name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: '3.35.4'
          channel: stable
          cache: false
          force-install: true

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
